Repository elixirschool/school_house, pull requests merged in 2021-04, with the labels that each got.

#24 fixes HTML structure on lesson menu
  lib/school_house_web/templates/layout/_lesson_menu.html.leex
Labels: elixir, enhancement, tailwind

#23 configures production as explained in guides for Heroku
  config/prod.exs
Labels: elixir, enhancement

#30 Testing enhancements
  config/config.exs
  config/test.exs
  lib/school_house/lessons.ex
  lib/school_house/posts.ex
  test/school_house/lessons_test.exs
  test/school_house/posts_test.exs
  test/support/content/lessons/en/basics/basics.md
  test/support/content/lessons/es/basics/basics.md
  test/support/content/posts/test_blog_post.md
Labels: elixir, enhancement

#29 Update scroll to top link with an arrow
  lib/school_house_web/templates/lesson/_section_header.html.eex
Labels: enhancement, tailwind

#33 Correct invalid lesson name in configuration
  config/lessons.exs
Labels: bug, elixir

#31 Update CODEOWNERS for initial development group
  .github/CODEOWNERS
Labels: enhancement

#25 We only need to modify the path
  lib/school_house_web/templates/layout/_locale_menu.html.leex
  lib/school_house_web/views/html_helpers.ex
  test/school_house_web/views/html_helpers_test.exs
Labels: bug, elixir

#34 Fix arithmetic error & update `Lessons.get/3`
  lib/school_house/lessons.ex
  lib/school_house_web/controllers/fallback_controller.ex
  lib/school_house_web/controllers/lesson_controller.ex
  lib/school_house_web/templates/error/error.html.eex
  lib/school_house_web/templates/error/translation_missing.html.eex
  lib/school_house_web/templates/layout/root.html.leex
  lib/school_house_web/templates/post/_post_preview.html.eex
  lib/school_house_web/views/error_view.ex
  test/school_house/lessons_test.exs
  test/school_house_web/controllers/lesson_controller_test.exs
  test/school_house_web/controllers/post_controller_test.exs
  test/school_house_web/views/error_view_test.exs
  test/support/content/lessons/en/basics/collections.md
  test/support/content/lessons/en/basics/enum.md
  test/support/content/lessons/es/basics/collections.md
  test/support/content/lessons/es/basics/enum.md
Labels: bug, elixir, enhancement, tailwind

#46 Add Dialyzer to CI pipeline
  .github/workflows/ci.yml
  mix.exs
  mix.lock
Labels: elixir, enhancement

#39 Translation report
  lib/school_house/content/lesson.ex
  lib/school_house/lessons.ex
  lib/school_house_web/controllers/page_controller.ex
  lib/school_house_web/controllers/report_controller.ex
  lib/school_house_web/router.ex
  lib/school_house_web/templates/layout/_footer.html.leex
  lib/school_house_web/templates/report/_coming_soon.html.eex
  lib/school_house_web/templates/report/_lesson.html.eex
  lib/school_house_web/templates/report/_missing.html.eex
  lib/school_house_web/templates/report/_section.html.eex
  lib/school_house_web/templates/report/report.html.eex
  lib/school_house_web/views/html_helpers.ex
  lib/school_house_web/views/report_view.ex
  priv/gettext/default.pot
  priv/gettext/en/LC_MESSAGES/default.po
  test/school_house/lessons_test.exs
Labels: elixir, enhancement, tailwind
