Repository elixirschool/school_house, pull requests merged in 2021-06, with the labels that each got.

#58 Add Conferences Page
  config/config.exs
  config/test.exs
  lib/school_house/conferences.ex
  lib/school_house/content/conference.ex
  lib/school_house_web/controllers/live/conference_live/index.ex
  lib/school_house_web/controllers/live/conference_live/index.html.leex
  lib/school_house_web/controllers/page_controller.ex
  lib/school_house_web/router.ex
  lib/school_house_web/templates/layout/_footer.html.leex
  lib/school_house_web/templates/page/conferences.html.eex
  mix.exs
  mix.lock
  test/school_house/conferences_test.exs
  test/school_house_web/controllers/live/conference_live/index_test.exs
  test/support/content/conferences/test_in_person_conference.md
  test/support/content/conferences/test_online_conference.md
  test/test_helper.exs
Labels: elixir, enhancement, tailwind

#60 Introduce Makefile for easy setup
  .dockerignore
  Dockerfile
  Makefile
  README.md
  lib/school_house.ex
  lib/school_house_web.ex
Labels: elixir, enhancement

#65 Improve Responsiveness
  assets/css/app.css
  assets/js/app.js
  assets/js/dark-mode.js
  assets/js/menu-toggle.js
  assets/tailwind.config.js
  lib/school_house_web/templates/layout/_dark_mode_toggle.html.leex
  lib/school_house_web/templates/layout/_header.html.leex
  lib/school_house_web/templates/layout/_lesson_menu.html.leex
  lib/school_house_web/templates/lesson/lesson.html.eex
  lib/school_house_web/templates/page/index.html.eex
  lib/school_house_web/templates/page/why.html.eex
  lib/school_house_web/templates/post/index.html.eex
Labels: enhancement, tailwind

#67 Update Dockerfile to Resolve Deploy Issue
  .dockerignore
  Dockerfile
  Makefile
Labels: bug

#68 Remove Duplicate ids From Dark Mode Toggle and Locale Menu
  lib/school_house_web/templates/layout/_dark_mode_toggle.html.leex
  lib/school_house_web/templates/layout/_locale_menu.html.leex
Labels: enhancement
