Repository elixirschool/school_house, pull requests merged in 2021-10, with the labels that each got.

#150 Remove newsletter signup
  lib/school_house_web/templates/page/index.html.eex
Labels: enhancement, elixir, hacktoberest-accepted

#155 Wrong URL to edit lessons
  lib/school_house_web/templates/lesson/lesson.html.heex
Labels: bug, hacktoberest-accepted

#158 Fix typos in lesson links
  lib/school_house_web/templates/layout/_lesson_menu.html.heex
Labels: bug, hacktoberest-accepted

#152 Add pagination to blog posts page
  lib/school_house_web/templates/post/index.html.heex
Labels: enhancement, tailwind, elixir

#157 update ROCKET-VALIDATOR.md
  ROCKET-VALIDATOR.md
Labels: rocket validator, hacktoberest-accepted

#183 Add start server command
  README.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#184 Improve Repo Hygiene
  .credo.exs
  .gitignore
  README.md
  app.json
  test/school_house/conferences_test.exs
Labels: documentation, enhancement, elixir, hacktoberfest, hacktoberfest-accepted
