Repository elixirschool/school_house, pull requests merged in 2021-07, with the labels that each got.

#64 Sitemap generator
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  Makefile
  lib/mix/tasks/school_house.gen.rss.ex
  lib/mix/tasks/school_house.gen.sitemap.ex
  lib/school_house/content/post.ex
  lib/school_house_web/endpoint.ex
  lib/school_house_web/router.ex
  lib/school_house_web/templates/layout/_footer.html.leex
  mix.exs
  test/school_house/conferences_test.exs
  test/school_house_web/controllers/live/conference_live/index_test.exs
  test/support/content/posts/2021-06-13-test_blog_post.md
Labels: elixir, enhancement

#72 Add 'By The Numbers' Section to Home Page
  lib/school_house_web/templates/page/index.html.eex
Labels: enhancement

#91 Add "Get Involved" Page
  lib/school_house_web/controllers/page_controller.ex
  lib/school_house_web/router.ex
  lib/school_house_web/templates/error/error.html.eex
  lib/school_house_web/templates/error/translation_missing.html.eex
  lib/school_house_web/templates/layout/_footer.html.leex
  lib/school_house_web/templates/layout/_header.html.leex
  lib/school_house_web/templates/page/get_involved.html.eex
  lib/school_house_web/templates/page/index.html.eex
  test/school_house_web/controllers/page_controller_test.exs
Labels: enhancement, tailwind

#89 Fix Dark Mode Flicker and Handle Invalid Locales
  assets/js/dark-mode.js
  assets/js/initialize-theme.js
  assets/webpack.config.js
  lib/school_house_web/plugs/set_locale_plug.ex
  lib/school_house_web/templates/layout/_locale_menu.html.leex
  lib/school_house_web/templates/layout/root.html.leex
  lib/school_house_web/views/html_helpers.ex
  test/school_house_web/controllers/lesson_controller_test.exs
  test/school_house_web/views/html_helpers_test.exs
Labels: bug, tailwind

#95 fixes invalid meta tag for csrf token
  lib/school_house_web.ex
  lib/school_house_web/templates/layout/root.html.leex
Labels: rocket validator

#98 fixes language code for Greek
  config/config.exs
  config/redirects.exs
Labels: bug

#102 update muting rules used in rocket validator
  ROCKET-VALIDATOR.md
Labels: rocket validator

#103 adds missing id for country select in conferences page
  lib/school_house_web/live/conferences_live.html.leex
Labels: rocket validator

#104 replace nprogress with topbar
  assets/js/app.js
  assets/package-lock.json
  assets/package.json
Labels: rocket validator

#110 adds missing alt for images in podcasts page
  lib/school_house_web/templates/page/podcasts.html.eex
Labels: rocket validator

#113 Add Sitemap Links for Dark Mode
  .gitignore
  lib/mix/tasks/school_house.gen.sitemap.ex
  lib/school_house_web/endpoint.ex
  lib/school_house_web/templates/layout/root.html.leex
  lib/school_house_web/views/layout_view.ex
  test/school_house_web/views/layout_view_test.exs
Labels: enhancement, rocket validator

#112 Better Text Contrast
  assets/css/app.css
  assets/tailwind.config.js
  lib/school_house_web/templates/layout/_footer.html.leex
  lib/school_house_web/templates/layout/_locale_menu.html.leex
  lib/school_house_web/templates/lesson/lesson.html.eex
  lib/school_house_web/templates/page/index.html.eex
  lib/school_house_web/templates/post/_post_preview.html.eex
Labels: rocket validator, tailwind
