Repository elixirschool/school_house, pull requests merged in 2021-08, with the labels that each got.

#119 Only Attempt a Deploy When Main Repo is Updated
  .github/workflows/deploy.yml
Labels: bug

#122 Fix Lesson TOC Issue With Intl Characters
  config/test.exs
  lib/school_house/content/lesson.ex
  test/school_house/content/lesson_test.exs
  test/support/content/lessons/en/basics/basics.md
  test/support/content/lessons/es/basics/collections.md
  test/support/content/lessons/ko/basics/collections.md
Labels: bug

#124 Update Color Scheme on Report Page
  assets/css/app.css
  lib/school_house_web/templates/report/_lesson.html.eex
  lib/school_house_web/templates/report/_missing.html.eex
  lib/school_house_web/templates/report/_section.html.eex
  lib/school_house_web/templates/report/report.html.eex
  lib/school_house_web/views/html_helpers.ex
Labels: tailwind, rocket validator

#126 Fix Remaining Contrast Issues for Dark Theme
  assets/tailwind.config.js
  lib/school_house_web/templates/lesson/_testing.html.eex
  lib/school_house_web/templates/page/_newsletter.html.eex
Labels: bug, tailwind, rocket validator

#125 Adds ability to filter posts by tag and updates footer blog links
  lib/school_house/posts.ex
  lib/school_house_web/controllers/post_controller.ex
  lib/school_house_web/router.ex
  lib/school_house_web/templates/layout/_footer.html.leex
  lib/school_house_web/templates/post/_post_preview.html.eex
  lib/school_house_web/templates/post/index.html.eex
  test/school_house/posts_test.exs
  test/school_house_web/controllers/post_controller_test.exs
  test/support/content/posts/2021-08-11-another_test_blog_post.md
Labels: enhancement, elixir

#129 Remove Extra Paragraph Tag from Lesson Section Index Page
  lib/school_house_web/templates/lesson/index.html.eex
Labels: bug, rocket validator
