Repository elixirschool/school_house, pull requests merged in 2021-09, with the labels that each got.

#130 Update Excerpt Link Color, Code Blocks
  assets/css/app.css
Labels: rocket validator

#132 Remove Ecto Dependency and Related Files
  .formatter.exs
  config/config.exs
  config/dev.exs
  lib/school_house/application.ex
  lib/school_house/repo.ex
  lib/school_house_web/endpoint.ex
  mix.exs
  mix.lock
  priv/repo/migrations/.formatter.exs
  priv/repo/seeds.exs
  test/support/data_case.ex
Labels: elixir

#134 The existing site includes /lessons
  lib/school_house_web/router.ex
Labels: bug

#140 Upgrade to Phoenix 1.6.0
  Dockerfile
  Makefile
  assets/.babelrc
  assets/js/app.js
  assets/package-lock.json
  assets/package.json
  assets/webpack.config.js
  config/config.exs
  config/dev.exs
  lib/school_house_web/endpoint.ex
  lib/school_house_web/live/conferences_live.html.heex
  lib/school_house_web/router.ex
  lib/school_house_web/templates/layout/_locale_menu.html.leex
  lib/school_house_web/templates/layout/root.html.leex
  mix.exs
  mix.lock
Labels: enhancement, tailwind, elixir

#146 Update Stream Data Lesson Redirect
  config/redirects.exs
  test/school_house_web/controllers/lesson_controller_test.exs
Labels: bug

#147 Fix Image Assets After Upgrade to Phoenix 1.6
  .gitignore
  Makefile
  assets/static/favicon.ico
  assets/tailwind.config.js
  lib/school_house_web/endpoint.ex
  lib/school_house_web/live/conferences_live.html.heex
  lib/school_house_web/templates/layout/root.html.leex
  mix.exs
Labels: bug, tailwind, elixir
