Repository elixirschool/school_house, pull requests merged in 2022-10, with the labels that each got.

#202 🐛 Fix "Coming Soon" badge translation in Lesson popover
  lib/school_house_web/templates/report/_coming_soon.html.heex
  lib/school_house_web/views/html_helpers.ex
  priv/gettext/ar/LC_MESSAGES/default.po
  priv/gettext/bg/LC_MESSAGES/default.po
  priv/gettext/bn/LC_MESSAGES/default.po
  priv/gettext/de/LC_MESSAGES/default.po
  priv/gettext/default.pot
  priv/gettext/el/LC_MESSAGES/default.po
  priv/gettext/en/LC_MESSAGES/default.po
  priv/gettext/es/LC_MESSAGES/default.po
  priv/gettext/fr/LC_MESSAGES/default.po
  priv/gettext/id/LC_MESSAGES/default.po
  priv/gettext/it/LC_MESSAGES/default.po
  priv/gettext/ja/LC_MESSAGES/default.po
  priv/gettext/ko/LC_MESSAGES/default.po
  priv/gettext/ms/LC_MESSAGES/default.po
  priv/gettext/no/LC_MESSAGES/default.po
  priv/gettext/pl/LC_MESSAGES/default.po
  priv/gettext/pt/LC_MESSAGES/default.po
  priv/gettext/ru/LC_MESSAGES/default.po
  priv/gettext/sk/LC_MESSAGES/default.po
  priv/gettext/ta/LC_MESSAGES/default.po
  priv/gettext/th/LC_MESSAGES/default.po
  priv/gettext/tr/LC_MESSAGES/default.po
  priv/gettext/uk/LC_MESSAGES/default.po
  priv/gettext/vi/LC_MESSAGES/default.po
Labels: hacktoberfest-accepted

#201 🌐 Add norwegian translation for web page
  lib/school_house_web/templates/page/index.html.heex
  priv/gettext/no/LC_MESSAGES/default.po
Labels: hacktoberfest-accepted

#206 Upgrade npm packages related to Tailwind
  assets/package-lock.json
  assets/package.json
  assets/tailwind.config.js
  lib/school_house_web/templates/post/_post_preview.html.heex
Labels: hacktoberfest, hacktoberfest-accepted

#207 Default to Device Preference for Site Theme
  assets/js/dark-mode.js
  priv/gettext/no/LC_MESSAGES/default.po
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#205 Upgrade to Elixir v1.14
  .github/workflows/ci.yml
  .tool-versions
  Dockerfile
  lib/school_house/lessons.ex
  lib/school_house_web/views/layout_view.ex
  mix.exs
  mix.lock
Labels: hacktoberfest, hacktoberfest-accepted
